# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_machine_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ftype', models.CharField(max_length=64, verbose_name='\u670d\u52a1\u5668\u7c7b\u578b')),
                ('Fserver_host', models.CharField(max_length=32, verbose_name='IP')),
                ('Fserver_port', models.IntegerField(default=3306, verbose_name='\u7aef\u53e3')),
                ('Fstate', models.CharField(max_length=16, verbose_name='\u673a\u5668\u72b6\u6001')),
                ('Fcreate_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('Fmodify_time', models.DateTimeField(auto_now_add=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
    ]
